name: Make a release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install prerequisites
      run: sudo apt-get install -y debootstrap squashfs-tools

    - name: Build a release image
      run: sudo ./build.sh /tmp/tt-rss.raw

    - name: Create a github release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /tmp/tt-rss.raw
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
