name: Make a release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=https://github.com/gdamjan/nixpkgs/archive/fix-uwsgi-php-try3.tar.gz

    - run: nix-build

    - run: |
        cp result tt-rss.raw

    - name: Create a github release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: tt-rss.raw
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
